server:
  port: 8081
  path: v0/
  error.include-message: always
  filecache: ./localfilecache/

spring:
  datasource:
    auth: false
    scheme: "jdbc:postgresql"
    path: localhost
    port: 5432
    database:
      name: messageboard
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner.location: classpath:banner.txt

auth0:
  audience: "http://127.0.0.1:8081/v0"
  issuer-uri: "https://dev-9deub659.us.auth0.com/"
  scope.secureroutes: "org.morriswa.messageboard:develop"

aws:
  secret-name: "messageboard/local"
  region: "us-east-2"
  s3:
    bucket: circlesdevocean

common:
  service:
    endpoints:
      health:
        path: health
        messages:
          get: "Hello! All is good on our side..."
      error:
        path: error
        messages:
          get: "Oh no! That page was not found :("
    errors:
      bad-datasource-config: "DATASOURCE COULD NOT BE CONFIGURED, PLEASE CHECK CONFIG <3"
      validation-exception-thrown: A validation exception has occurred!
      security:
        not-allowed: YOU SHALL NOT PASS!
        not-allowed-desc: The requested service requires authorization, which you didn't bother to provide
        invalid-jwt: "invalid jwt :("
        scope-error-message: The requested service requires a higher scope than you provided.
      audience:
        code: invalid_token
        error: The required audience is missing

user-profile:
  service:
    endpoints:
      user:
        path: user
        messages:
          get: Successfully retrieved user profile
          post: Successfully registered new user %s!
      user-profile-image:
        path: user/profileImage
        messages:
          get: Successfully retrieved user profile image
          post: Successfully updated user profile image
      user-profile-displayname:
        path: user/displayName
        messages:
          patch: "Successfully updated user's display name"
    errors:
      missing-user: No registered user
      bad-image-format: "*** COULD NOT SAVE FILE WITH FORMAT: %s ***"
      unable-to-delete-cached-file: Could not delete cached file...
      display-name-already-exists: Could not update your display name because another user is already registered with that display name!
      bad-display-name: "Alphanumeric chars, underscores, hyphens and periods only please."
      bad-display-name-length: "Display Name should be at least 3 and not more than 30 chars."
    stores:
      profile-images: "user-content/profiles/"
      default-profile-image: "static-content/DEFAULT_USER_PROFILE_0"
    rules:
      display-name:
        regexp: "^[A-Za-z0-9._-]*$"
        min-length: 3
        max-length: 30
      user-profile-image-dimension: 256

community:
  service:
    endpoints:
      community:
        path: community
        messages:
          post: "Your community has successfully been registered!"
          get: "Successfully retrieved requested information!"
      community-membership:
        path: community/{communityId}/membership
        messages:
          post: "You have successfully joined the requested community!"
          delete: "You have successfully left the requested community"
      update-community-banner:
        path: community/{communityId}/banner
        messages:
          post: "Your community banner was changed successfully!"
      update-community-icon:
        path: community/{communityId}/icon
        messages:
          post: "Your community icon was changed successfully!"
      get-users-communities:
        path: communities
        messages:
          get: "Successfully retrieved all of users' communities"
    errors:
      missing-community: "We could not locate a community named %s :("
      missing-community-by-id: "We could not locate a community #%s :("
      not-community-owner: You cannot perform this action because this community does not exist or because you are not the community owner.
      no-relation-found: You do not appear to be a part of this community!
      user-cannot-post: You are not authorized to post to this community!
    stores:
      icons: "user-content/communities/icons/"
      banners: "user-content/communities/banners/"

content:
  service:
    endpoints:
      create-post:
        path: community/{communityId}/post
        messages:
          post: Good!
      community-feed:
        path: community/{communityId}/feed
        messages:
          get: Good!
    errors:
      content-type-not-supported: Sorry! The content you attempted to upload is not yet supported by this application
      too-many-images: Please do not upload more than 10 images for a single post!
    stores:
      resources: "user-content/post/resources/"
