
server:
  port: 8081
  path: v0/
  error.include-message: always

spring:
  datasource:
    auth: false
    scheme: "jdbc:postgresql"
    path: localhost
    port: 5432
    database:
      name: messageboard
  banner.location: classpath:banner.txt
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

auth0:
  audience: "http://127.0.0.1:8081/v0"
  issuer-uri: "https://dev-9deub659.us.auth0.com/"
  rbac:
    permissions: "org.morriswa.messageboard:test org.morriswa.messageboard:develop"

aws:
  secret-name: "messageboard/local"
  region: "us-east-2"
  s3:
    bucket: circlesdevocean

testing:
  email: test@email.com

common:
  date-format: yyyy-M-d
  youngest: 2010-1-1
  public: >
    /health
    /feed
    /preferences
  cache: ./localfilecache/
  stores:
    prefix: developer-content
    profile-images: "/profiles/"
    community-icons: "/communities/icons/"
    community-banners: "/communities/banners/"
    post-resources: "/post/resources/"
  static-content:
    default-profile-image: "static-content/DEFAULT_USER_PROFILE_0"
    default-community-icon: "static-content/DEFAULT_COMMUNITY_ICON_0"
  service:
    rules:
      square-icon-image-dimension: 512
      signed-url-expiration-minutes: 60
    endpoints:
      health:
        path: health
        messages:
          get: "Hello! All is good on our side..."
      error:
        path: error
        messages:
          get: "Oh no! That page was not found :("
      preferences:
        path: preferences
        messages:
          get: Got application preferences!!
      recent-post-feed:
        path: feed
        messages:
          get: Successfully retrieved post feed
    errors:
      bad-datasource-config: "DATASOURCE COULD NOT BE CONFIGURED, PLEASE CHECK CONFIG <3"
      validation-exception-thrown: A validation exception has occurred!
      permissions-exception-thrown: "You do not have appropriate permissions to perform this action!"
      security:
        not-allowed: YOU SHALL NOT PASS!
        not-allowed-desc: The requested service requires authorization, which you didn't bother to provide
        invalid-jwt: "invalid jwt :("
        scope-error-message: The requested service requires a higher scope than you provided.
      audience:
        code: invalid_token
        error: The required audience is missing
      unable-to-delete-cached-file: Could not delete cached file...
      failed-to-cache-file: Could not cache file...
      upload-image-request:
        empty-image-format: image format must NOT be empty
        bad-image-repr: image blob must NOT be empty
        bad-image-format: image format must NOT be %s! convert this on the front please :)

user-profile:
  service:
    endpoints:
      user:
        path: user
        messages:
          get: Successfully retrieved user profile
          post: Successfully registered new user %s!
      user-ui:
        path: user/ui
        messages:
          get: Successfully retrieved user ui profile
          patch: Successfully updated users UI profile
      user-profile-image:
        path: user/profileImage
        messages:
          get: Successfully retrieved user profile image
          post: Successfully updated user profile image
      user-profile-displayname:
        path: user/displayName
        messages:
          patch: "Successfully updated user's display name"
    errors:
      missing-user: No registered user
      display-name-already-exists: Could not update your display name because another user is already registered with that display name!
      bad-display-name: "Alphanumeric chars, underscores, hyphens and periods only please."
      bad-display-name-length: "Display Name should be at least %s and not more than %s chars."
      too-young: You must be born before %s to join :(
    rules:
      display-name:
        regexp: "^[A-Za-z0-9._-]*$"
        min-length: 3
        max-length: 30
      default-theme: default

community:
  service:
    endpoints:
      community:
        path: community
        messages:
          post: "Your community has successfully been registered!"
          get: "Successfully retrieved requested information!"
          patch: "Successfully updated requested information!"
      member:
        path: community/{communityId}/member
        messages:
          post: "You have successfully joined the requested community!"
          delete: "You have successfully left the requested community"
      watcher:
        path: community/{communityId}/status
        messages:
          get: Retrieved current community watcher info
      member-details:
        path: community/{communityId}/member/{userId}
        messages:
          get: Retrieved member info
      community-moderation:
        path: community/{communityId}/mod
        messages:
          patch: You have successfully updated user's moderation status!
          get: Successfully retrieved Community's Moderators
      update-community-banner:
        path: community/{communityId}/banner
        messages:
          post: "Your community banner was changed successfully!"
      update-community-icon:
        path: community/{communityId}/icon
        messages:
          post: "Your community icon was changed successfully!"
      get-users-communities:
        path: communities
        messages:
          get: "Successfully retrieved all of users' communities"
      search-communities:
        path: communities/search
        messages:
          get: Successfully retrieved search results
    rules:
      banner-scale-factor: 0.5
      display-name:
        min-length: 3
        max-length: 100
      community-ref:
        regexp: "^[a-z][a-z0-9-]*[a-z0-9]$"
        min-length: 4
        max-length: 30
    errors:
      missing-community: "We could not locate a community named %s :("
      missing-community-by-id: "We could not locate a community # %s :("
      no-relation-found: You do not appear to be a part of this community!
      user-not-in-community: This user does not appear to be part of your community.
      user-cannot-post: You are not authorized to post to this community!
      user-cannot-moderate: "User %s was denied %s access to community # %s"
      edit-owner: "Unable to modify the Permissions of the Community Owner!"
      edit-promoter: "Unable to change another Community Promoter's Permissions!"
      bad-community-ref-length: "Community locator must be between %s and %s characters!"
      bad-community-ref: Please only include lowercase letters, numbers, and hyphens!
        Additionally, your ref should not start or end with a hyphen, or start with a number. Thanks!
      bad-community-display-name-length: "Community display name must be between %s and %s characters!"
      ref-already-taken: "bad kitty that name is already taken"

content:
  service:
    endpoints:
      community-feed:
        path: community/{communityId}/feed
        messages:
          get: Good!
      post-details:
        path: post/{postId}
        messages:
          get: Successfully got post details
          delete: Successfully deleted post!
      comment:
        path: post/{postId}/comment
        messages:
          get: Successfully comments for post
          post: Successfully left comment on requested post
      sub-comment:
        path: post/{postId}/comment/{commentId}
        messages:
          get: Successfully retrieved sub comments
          post: Successfully replied to requested comment
          delete: Successfully deleted comment!
      post-voting:
        path: post/{postId}/vote
        messages:
          post: Successfully voted
      comment-voting:
        path: post/{postId}/comment/{commentId}/vote
        messages:
          post: Successfully voted
      draft:
        path: draft/{draftId}
        messages:
          get: FINE!
          post: Successfully created post, congrats!
          patch: FINE!
      add-content:
        path: draft/{draftId}/add
        messages:
          post: FINE!
      create-draft:
        path: community/{communityId}/draft
        messages:
          post: Draft session created!
    errors:
      cannot-locate-post: no post with id %d
      content-type-not-supported: Sorry! The content you attempted to upload is not yet supported by this application
      too-many-images: Please do not upload more than %d images for a single post!
      cannot-locate-resource: could not locate resource %s :(
      cannot-locate-session: could not locate post creation session :(
      null-comment: No null comments!!!
      bad-comment-length: Comments may not be more than %d characters!
    rules:
      image-scale-factor: 0.5
      max-allowed-content: 10
      caption:
        min-length: 10
        max-length: 200
      description:
        max-length: 10000
